package com.bigjelly.shaddockvideoplayer.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.bigjelly.shaddockvideoplayer.model.VideoFile;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "VIDEO_FILE".
*/
public class VideoFileDao extends AbstractDao<VideoFile, Long> {

    public static final String TABLENAME = "VIDEO_FILE";

    /**
     * Properties of entity VideoFile.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property FileID = new Property(0, Long.class, "fileID", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property Path = new Property(2, String.class, "path", false, "PATH");
        public final static Property Count = new Property(3, int.class, "count", false, "COUNT");
    }

    private DaoSession daoSession;


    public VideoFileDao(DaoConfig config) {
        super(config);
    }
    
    public VideoFileDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"VIDEO_FILE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: fileID
                "\"NAME\" TEXT," + // 1: name
                "\"PATH\" TEXT UNIQUE ," + // 2: path
                "\"COUNT\" INTEGER NOT NULL );"); // 3: count
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"VIDEO_FILE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, VideoFile entity) {
        stmt.clearBindings();
 
        Long fileID = entity.getFileID();
        if (fileID != null) {
            stmt.bindLong(1, fileID);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String path = entity.getPath();
        if (path != null) {
            stmt.bindString(3, path);
        }
        stmt.bindLong(4, entity.getCount());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, VideoFile entity) {
        stmt.clearBindings();
 
        Long fileID = entity.getFileID();
        if (fileID != null) {
            stmt.bindLong(1, fileID);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String path = entity.getPath();
        if (path != null) {
            stmt.bindString(3, path);
        }
        stmt.bindLong(4, entity.getCount());
    }

    @Override
    protected final void attachEntity(VideoFile entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public VideoFile readEntity(Cursor cursor, int offset) {
        VideoFile entity = new VideoFile( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // fileID
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // path
            cursor.getInt(offset + 3) // count
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, VideoFile entity, int offset) {
        entity.setFileID(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setPath(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setCount(cursor.getInt(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(VideoFile entity, long rowId) {
        entity.setFileID(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(VideoFile entity) {
        if(entity != null) {
            return entity.getFileID();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(VideoFile entity) {
        return entity.getFileID() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
